# cluster commands
cluster: 
  mkdir -p logs/cluster_logs/`date +"%Y-%m-%d"`/{rule} &&
  sbatch --job-name={rule}_{wildcards}
          --output=logs/cluster_logs/`date +"%Y-%m-%d"`/{rule}/{rule}-{wildcards}_%j.out
          --account=pschloss1 
          --partition=standard 
          --nodes=1 
          --time={resources.time_min} 
          --mem={resources.mem_mb}
          --cpus-per-task={resources.cpus} 

default-resources: [cpus=1, 
                    mem_mb=8000, 
                    time_min=2880,
                    job_name="rare"]


# snakemake args
jobs: 5000
scheduler: "greedy"
use-conda: true
conda-frontend: "mamba"
keep-going: true
latency-wait: 120
