name: rare
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - snakemake=7.3.8
  - sra-tools=2.11.0
  - mothur=1.47.0
  - r-base=4.1.3
  - r-renv=0.15.4 # willl load all other R packages with renv
