name: rare
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - snakemake=7.3.8
  - sra-tools=2.11.0
  - mothur=1.47.0
  - r-base=4.1.3
  - r-data.table=1.14.2
  - r-tidyverse=1.3.1
  - r-here=1.0.1
  - r-vegan=2.6-2
  - r-effectsize=0.7.0
  - r-SRS=0.2.3
  - r-breakaway=4.7.9
  - r-zcompositions=1.4.0
  - bioconductor-deseq2=1.34.0
  - bioconductor-metagenomeseq=1.36.0