name: rare
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - snakemake=7.3.1
  - sra-tools=2.11.0
  - mothur=1.47.0
  - r-base=4.1.3
  - r-tidyverse=1.3.1
  - r-data.table=1.14.2
  - r-breakaway=3.0
  # - bioconductor-phyloseq=1.38.0
  - bioconductor-deseq2=1.34.0
  - bioconductor-metagenomeseq=1.36.0
  - r-vegan=2.5_7
